spring:
  application:
    name: Tumo

  datasource:
    url: jdbc:postgresql://localhost:5432/tumo
    username: tumo
    password: tumo

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

server:
  port: 8080

jwt:
  secret: tumo-local-development-secret-key-must-be-at-least-32-bytes
  access-token-expiration-millis: 3600000
  refresh-token-expiration-millis: 1209600000
